version: 2
jobs:
  build:
    docker:
      - image: gcr.io/wptdashboard/wptd-testrun-circle
    environment:
      - TERM: linux
      - TERMINFO: /etc/terminfo
      - PLATFORM_ID: firefox-57.0-linux
      # We'd get this from the checkout normally (I think)
      - WPT_SHA: c2d0053cfa
      - RUN_PATH: shadow-dom
    working_directory: ~/repo
    parallelism: 3
    steps:
      - checkout
      - run:
          name: Run tests
          command: python /run.py
